### PR TITLE
Bump version to 20191125

### PR DESCRIPTION
**Pull request by nehaljwani**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by nehaljwani** [comment]
@conda-forge/pdfminer This MR closes https://github.com/conda-forge/pdfminer-feedstock/pull/7 and https://github.com/conda-forge/pdfminer-feedstock/pull/6 and adds py3 support :)

**Comment by beckermr** [comment]
The core team generally waits a week on merge requests like this. If you need it sooner, let us know!

**Comment by beckermr** [comment]
Ohhh looks like you did add yourself as a maintainer. Happy to merge sooner.

**Comment by nehaljwani** [comment]
Thank you @beckermr !

**Pull request merged**
